interioer-concept:
	xelatex interioer-concept.tex
clean:
	rm \
		interioer-concept.aux \
		interioer-concept.dvi \
		interioer-concept.fdb_latexmk \
		interioer-concept.fls \
		interioer-concept.log \
		interioer-concept.out \
		interioer-concept.pdf \
		interioer-concept.synctex.gz \
		interioer-concept.toc
